export const REQUEST_BOARD_UPDATE = 'REQUEST_BOARD_UPDATE'
export const BOARD_UPDATE_RECEIVED = 'BOARD_UPDATE_RECEIVED'
export const REQUEST_HIGHSCORE_UPDATE = 'REQUEST_HIGHSCORE_UPDATE'
export const HIGHSCORE_UPDATE_RECEIVED = 'HIGHSCORE_UPDATE_RECEIVED'